server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://192.168.127.3:27017
      database: xc_cms
  rabbitmq:
    host: 192.168.127.3
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000