server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://192.168.127.3:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 192.168.127.3
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: E:/IDEA/workspace/xc-springcloud/video/
  ffmpeg-path: E:/ffmpeg/bin/ffmpeg.exe